services:
  - type: web
    name: mahmoud-zanaty-portfolio
    env: static
    buildCommand: ""
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
